onlydustxyz/marketplace-starknet

.gitignore, .gitmodules, contracts/onlydust/deathnote/core/badge/badge.cairo, contracts/onlydust/deathnote/core/badge/badge_library.cairo, contracts/onlydust/deathnote/core/badge/library.cairo, contracts/onlydust/deathnote/core/badge/test_badge.cairo, contracts/onlydust/deathnote/core/badge/test_badge.e2e.cairo, contracts/onlydust/deathnote/interfaces/badge.cairo, protostar.toml
- add cairo_contracts
- :sparkles: badge is a mintable NFT
=> initiate badge NFT contract

CONTRIBUTING.md, contracts/onlydust/deathnote/core/badge/badge.cairo, contracts/onlydust/deathnote/core/badge/library.cairo, contracts/onlydust/deathnote/core/badge/test_badge.cairo, contracts/onlydust/deathnote/core/badge/test_badge.e2e.cairo, contracts/onlydust/deathnote/interfaces/badge.cairo, contracts/onlydust/deathnote/library/accesscontrol.cairo
closes #4
- add cairo_contracts
- :sparkles: badge is a mintable NFT
- :pencil2: rename variables to follow naming convention
- :memo: Add missing CONTRIBUTING.md
- :sparkles: add access control for badge
=> create badge smart contract

contracts/onlydust/deathnote/core/badge/test_badge.e2e.cairo, contracts/onlydust/deathnote/core/badge_registry/badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/badge_registry_library.cairo, contracts/onlydust/deathnote/core/badge_registry/library.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.e2e.cairo, contracts/onlydust/deathnote/interfaces/badge.cairo, contracts/onlydust/deathnote/interfaces/badge_registry.cairo
=> create badge registry smart contract

contracts/onlydust/deathnote/core/badge_registry/badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/library.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.e2e.cairo, contracts/onlydust/deathnote/interfaces/badge_registry.cairo
=> add reverse mapping from github handle in badge registry

contracts/onlydust/deathnote/core/badge_registry/badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/library.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.cairo, contracts/onlydust/deathnote/core/badge_registry/test_badge_registry.e2e.cairo, contracts/onlydust/deathnote/interfaces/badge_registry.cairo, contracts/onlydust/deathnote/test/test_e2e.cairo
=> move access control of badge registry to role-based method

contracts/onlydust/deathnote/core/contributions/github/github.cairo, contracts/onlydust/deathnote/core/contributions/github/library.cairo, contracts/onlydust/deathnote/core/contributions/github/test_github.cairo, contracts/onlydust/deathnote/core/contributions/github/test_github.e2e.cairo, contracts/onlydust/deathnote/interfaces/contributions/github.cairo, contracts/onlydust/deathnote/test/test_e2e.cairo
=> :sparkles: add possibility to add contribution from github handle

contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/test/libraries/contributions.cairo
=> As a feeder I want to create a gated contribution

contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/deathnote/interfaces/contributions.cairo
closes #36
- :sparkles: feeder can validate a contribution
- :sparkles: increase past contributions count upon validation
=> as a feeder I can mark a contribution as completed

contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/deathnote/interfaces/contributions.cairo
=> :sparkles: anyone can list contributions currently assigned to a given contributor

contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/deathnote/interfaces/contributions.cairo, contracts/onlydust/deathnote/test/test_e2e.cairo
- Closes #50 
- Fixes `contribution_count_required` validation
- Changes `new_contribution` interface and related tests
=> Anyone can list eligible contributions

contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/interfaces/contributions.cairo
=> ✨ Add past_contributions view

contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/deathnote/interfaces/contributions.cairo, contracts/onlydust/deathnote/test/libraries/contributions.cairo, contracts/onlydust/deathnote/test/test_e2e.cairo
Co-authored-by: Timothée Delabrouille <tdelabro@users.noreply.github.com>
=> ✨ add validator_account feature for contribution

contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.e2e.cairo
Co-authored-by: Timothée Delabrouille <tdelabro@users.noreply.github.com>
=> ✨ Validate with validator

.gitmodules, README.md, contracts/onlydust/deathnote/core/contributions/contributions.cairo, contracts/onlydust/deathnote/core/profile/library.cairo, protostar.toml, scripts/deploy.sh
AADeveloper, when I deploy a new version of a contract, I see on voyager that old data is still accessible through a proxy contract
=> Allows to deploy and update proxy contracts. Also allows to deploy on devnet

contracts/onlydust/deathnote/core/contributions/library.cairo, contracts/onlydust/deathnote/core/contributions/test_contributions.cairo
Possibility to add 0x0 validator_account in case only ADMIN validates.
=> Fix: fix validator_account logic

.github/workflows/devnet-dump-assets/starknet_open_zeppelin_accounts.json, .github/workflows/devnet.yml, scripts/deploy.sh, scripts/tools.sh
depends on https://github.com/onlydustxyz/starknet-accounts/pull/4
=> 👷 create devnet-dump for e2e tests in CI

contracts/onlydust/marketplace/core/contributions/contributions.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/marketplace/interfaces/contributions.cairo
Started a new pr for #69 since there was a refactor. Set contributions values to 0. Set the status to NONE not sure if it also should be 0. 
Will add more tests if this implementation looks good.
@AnthonyBuisset
=> add remove_contributions

contracts/onlydust/marketplace/core/contributions/contributions.cairo, contracts/onlydust/marketplace/core/contributions/contributions_migration.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/marketplace/interfaces/contributions.cairo, contracts/onlydust/marketplace/test/test_e2e.cairo
refactor: rename gate parameter
=> feat: change new_contribution signature

contracts/onlydust/marketplace/core/contributions/access_control.cairo, contracts/onlydust/marketplace/core/contributions/contributions.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_access_control.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.cairo, contracts/onlydust/marketplace/interfaces/contributions.cairo, contracts/onlydust/marketplace/test/test_e2e.cairo
- ✨ add member to project
- ✅ add e2e test for add_member_for_project
=> add project member

contracts/onlydust/marketplace/core/contributions/access_control.cairo, contracts/onlydust/marketplace/core/contributions/contributions.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_access_control.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/marketplace/interfaces/contributions.cairo
- ✨ claim contribution
- ✨ lead contributors can also claim
=> Claim contributions

.github/workflows/ci.yml, .github/workflows/devnet.yml, .gitmodules, contracts/onlydust/marketplace/core/contributions/access_control.cairo, contracts/onlydust/marketplace/core/contributions/contributions.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_access_control.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions.e2e.cairo, contracts/onlydust/marketplace/core/profile/library.cairo, contracts/onlydust/marketplace/core/profile/profile.cairo, contracts/onlydust/marketplace/core/profile/test_profile.cairo, contracts/onlydust/marketplace/core/profile/test_profile.e2e.cairo, contracts/onlydust/marketplace/core/registry/library.cairo, contracts/onlydust/marketplace/core/registry/registry.cairo, contracts/onlydust/marketplace/core/registry/test_registry.cairo, contracts/onlydust/marketplace/core/registry/test_registry.e2e.cairo, contracts/onlydust/marketplace/interfaces/contributions.cairo, contracts/onlydust/marketplace/interfaces/profile.cairo, contracts/onlydust/marketplace/interfaces/registry.cairo, contracts/onlydust/marketplace/library/migration_library.cairo, contracts/onlydust/marketplace/test/libraries/contributions.cairo, contracts/onlydust/marketplace/test/libraries/user.cairo, contracts/onlydust/marketplace/test/test_e2e.cairo, protostar.toml, scripts/deploy.sh
- ⬆️ update to Cairo 0.10.0
- ⬆️ update protostar
- 🔨 update deploy script
- 💚 update CI to work with cairo 0.10.0
=> Update to Cairo 0.10.0

contracts/onlydust/marketplace/core/github/contribution.cairo, contracts/onlydust/marketplace/core/github/test_contribution.cairo, contracts/onlydust/marketplace/interfaces/assignment_strategy.cairo, contracts/onlydust/marketplace/interfaces/contribution.cairo, contracts/onlydust/marketplace/interfaces/contributor_oracle.cairo, contracts/onlydust/marketplace/interfaces/onlydust.cairo, contracts/onlydust/marketplace/interfaces/project.cairo, protostar.toml
- ✨ introduce new contribution contract with assign function
- ✨ implement unassign in contribution
- ✨ implement validate in contribution
- ✨ add modify_gate to contribution
- ✨ add delete to contribution
=> Simple implementation of contribution contract

contracts/onlydust/marketplace/core/assignment_strategies/composite.cairo, contracts/onlydust/marketplace/core/assignment_strategies/test_composite.cairo, contracts/onlydust/marketplace/core/contribution.cairo, contracts/onlydust/marketplace/core/project.cairo, contracts/onlydust/marketplace/core/test_contribution.cairo, contracts/onlydust/marketplace/interfaces/assignment_strategy.cairo, contracts/onlydust/marketplace/interfaces/contribution.cairo, protostar.toml, scripts/deploy.sh
feat: move init loop in composable stategy
=> build: add strategies to protostar

contracts/onlydust/marketplace/constants.cairo, contracts/onlydust/marketplace/core/assignment_strategies/access_control.cairo, contracts/onlydust/marketplace/core/contributions/library.cairo, contracts/onlydust/marketplace/core/contributions/test_contributions_e2e.cairo, contracts/onlydust/marketplace/library/array.cairo
- ✨ create array helper library
- ♻️ simplify calldata building
- ✨ plug access_control strategy in the factory function
=> plug access_control strategy in contribution factory function
